### ISSUE TITLE
Problems with Invalid item

### ISSUE THREAD

**Issue by N1kyZ** [GuizhanCraft/SlimefunTranslation#27]
### Checklist

- [X] You are using official version downloaded from Blob Builds ([blob.build](https://blob.build/)) or Guizhan Builds ([builds.guizhanss.com](https://builds.guizhanss.com))
- [X] You have verified the checksum of the downloaded file to ensure it is complete (only for Guizhan Builds)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

Well, I was testing the new translation addon and I decided to try translating an item and after I used the reload command, in the console there were several "Invalid item", I deleted the folder thinking that I had made a mistake and let a new one appear and even then it gave this error and the item was not translated.

### Reproduction Steps

1. Use /sftr translation reload
2. See the console

### Expected Behavior

Reload all item translations and make it work

### Error report

https://pastebin.com/EaPFiCcE

### Server Software

Purpur

### Minecraft Version

1.18.2

### Slimefun version

Purpur git-Purpur-1632 (MC: 1.18.2)
Slimefun DEV - 1104 (git c977454e)
Metrics-Module #29
Java 17

Installed Addons: (3)
SlimefunTranslation vDev - 2
Supreme vDEV - 29 (git f9e70053)
GeneticChickengineering vDev - 3

### Plugin version

SlimefunTranslation version Dev - 2

**Comment by N1kyZ** [comment]
![image](https://github.com/GuizhanCraft/SlimefunTranslation/assets/58773688/2e60912f-6025-4e38-843d-cd3e2a94d4b3)

![image](https://github.com/GuizhanCraft/SlimefunTranslation/assets/58773688/a2f35fd6-0aa1-43aa-8e39-34858cad4ef2)

**Comment by ybw0014** [comment]
Working on fix
