### ISSUE TITLE
With automatic update activated it does not work

### ISSUE THREAD

**Issue by N1kyZ** [GuizhanCraft/SlimefunTranslation#28]
### Checklist

- [X] You are using official version downloaded from Blob Builds ([blob.build](https://blob.build/)) or Guizhan Builds ([builds.guizhanss.com](https://builds.guizhanss.com))
- [X] You have verified the checksum of the downloaded file to ensure it is complete (only for Guizhan Builds)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

For the plugin to work, I have to disable auto-update: true to false to work normally

### Reproduction Steps

1. Just leave auto-update on true, something that comes standard. So just turn on the server and it won't work

### Expected Behavior

the plugin works normally

### Error report

https://pastebin.com/zAZaUW2F

### Server Software

Purpur

### Minecraft Version

1.18.2

### Slimefun version

[01:31:47 INFO]: Purpur git-Purpur-1632 (MC: 1.18.2)
[01:31:47 INFO]: Slimefun DEV - 1104 (git c977454e)
[01:31:47 INFO]: Metrics-Module #29
[01:31:47 INFO]: Java 17
[01:31:47 INFO]:
[01:31:47 INFO]: Installed Addons: (3)
[01:31:47 INFO]:   SlimefunTranslation vDev - 3
[01:31:47 INFO]:   Supreme vDEV - 29 (git f9e70053)
[01:31:47 INFO]:   GeneticChickengineering vDev - 3

### Plugin version

SlimefunTranslation version Dev - 3

**Comment by ybw0014** [comment]
your slimefun is not latest, download from https://blob.build/project/Slimefun4/Dev
