### ISSUE TITLE
The language doesn't change after you change the language of your settings in-game.

### ISSUE THREAD

**Issue by reamianv** [GuizhanCraft/SlimefunTranslation#43]
### Checklist

- [X] You are using official version downloaded from Blob Builds ([blob.build](https://blob.build/)) or Guizhan Builds ([builds.guizhanss.com](https://builds.guizhanss.com))
- [X] You have verified the checksum of the downloaded file to ensure it is complete (only for Guizhan Builds)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

I was obviously using the ko: en mapping to translate and use the language, and when I changed the SlimeFun language from ko -> en, the ko language I was using before was not changed to en. So I tried changing the language in the Minecraft in-game settings from korean -> english, and the language setting in the SlimeFun guide from korean to english, but it didn't change to english. So I thought it was weird, so I tried setting it to a language other than english, but the language of the items that looked Korean didn't change even if I set it to another language. 

To summarize, changing the language in the in-game , Slimefun settings does not change the language of the item to another language.

### Reproduction Steps

0. Language set After use command sf give Mcnick itemname
1. Change the Slimefun guide language, and minecraft game language
2. Check the item name. and lore
3. ReJoin
4. Check the item name and lore
5. Server Reboot 
6. Check the item name and lore
7. Delete the plugin and start the server
8. join
9. Check the item name and lore

### Expected Behavior

Item Lore and names should display correctly when the language is set to a different language.

### Server log

[[_Pastebin.com/KYKGebi7_](https://pastebin.com/KYKGebi7)]

### Server Software

Purpur

### Minecraft Version

1.20.1

### Slimefun version

build 1145

### Plugin version

build 21

**Comment by reamianv** [comment]
![2024-05-13_01 21 48](https://github.com/GuizhanCraft/SlimefunTranslation/assets/76400529/e54deac2-a040-4a18-986f-eb434a8e453a)
![2024-05-13_01 22 57](https://github.com/GuizhanCraft/SlimefunTranslation/assets/76400529/bb4098f2-b5ce-4350-889d-fdf6c46e34bc)
![2024-05-13_08 19 42](https://github.com/GuizhanCraft/SlimefunTranslation/assets/76400529/ac136554-8ec6-4acb-8c16-fd570735d32c)
![2024-05-13_08 24 41](https://github.com/GuizhanCraft/SlimefunTranslation/assets/76400529/6f94ccb8-f082-4b35-a001-06a0dfd3fa2e)
![2024-05-13_08 24 47](https://github.com/GuizhanCraft/SlimefunTranslation/assets/76400529/140883aa-2892-483f-97e4-6bcece193e9a)
![2024-05-13_08 35 22](https://github.com/GuizhanCraft/SlimefunTranslation/assets/76400529/87a0be92-1026-491b-b1ce-ef25df42c00b)

**Comment by ybw0014** [comment]
since the default translations only cover core slimefun items, you will need to contact the translation provider about the translation of addon items.
also, do not map other languages to English. Instead, change the server's default language in Slimefun config, and set player   language to server default. (Minecraft language has no effect on this plugin)

**Comment by reamianv** [comment]
As for translations, I'm slowly translating everything by hand (including additional addons) and haven't mapped other languages to English. In the Slimefun configuration, I've already set the default language of the server to ko.
